ENH Only query primary DB
silverstripe/silverstripe-hybridsessions pull request #114
Opened 2024-09-16 03:27 UTC by emteknetnz

Issue https://github.com/silverstripe/silverstripe-framework/issues/11352

2024-09-24 00:17 UTC, GuySartorelli requested changes

2024-09-24 00:17 UTC, GuySartorelli commented on src/Model/HybridSessionDataObject.php
> +    private static bool $must_use_primary_db = true;
Why? Add a code comment so it's clear why we're setting this to true. Also add to the `withPrimary()` call in `DatabaseStore`

2024-09-24 23:12 UTC, emteknetnz commented on src/Model/HybridSessionDataObject.php
> +    private static bool $must_use_primary_db = true;
Updated

2024-09-26 00:25 UTC, GuySartorelli requested changes

2024-09-26 00:25 UTC, GuySartorelli commented on src/Model/HybridSessionDataObject.php
> +    private static bool $must_use_primary_db = true;
The comment explains what this config property _does_ - but still doesn't say why we need it to be true for _this_ dataobject specifically. I assume it's something to do with ensuring session data doesn't go out of sync?

2024-09-26 03:21 UTC, emteknetnz commented on src/Model/HybridSessionDataObject.php
> +    private static bool $must_use_primary_db = true;
Updated

2024-09-26 21:51 UTC, GuySartorelli approved these changes
LGTM, will merge after framework PR

2024-10-10 21:57 UTC, merged