API Remove ReturnTypeWillChange annotation
silverstripe/silverstripe-hybridsessions pull request #79
Opened 2023-01-13 01:58 UTC by maxime-rainville

## Parent issue
https://github.com/silverstripeltd/product-issues/issues/645

2023-01-13 02:09 UTC, maxime-rainville commented on tests/McryptCryptoTest.php
> -class McryptCryptoTest extends SapphireTest
That test is testing deprecated logic and should be removed.

2023-01-23 23:06 UTC, GuySartorelli requested changes
In `CookieStore` you've changed some `$session_id` args to `string` but left others undefined (possibly in other classes too, I didn't look too closely). They should probably _all_ be changed to `string` if we're making that a requirement.

2023-01-23 23:06 UTC, ChloeSartorelli commented on src/HybridSession.php
> +    public function read(string $session_id): string|false
```suggestion
    public function read(string $session_id): string
```
This will never return false -  that would fail the `if ($data = $handler->read($session_id))` check, in which case an empty string gets returned at the end of the method.

2023-01-23 23:06 UTC, ChloeSartorelli commented on src/HybridSession.php
> +    public function gc(int $maxlifetime): int|false
```suggestion
    public function gc(int $maxlifetime): int
```
This never returns `false` - also is `false` even a valid return type for PHP 8.1? I thought that was introduced in 8.2

2023-01-23 23:06 UTC, GuySartorelli commented on src/Store/CookieStore.php
> +    public function gc(int $maxlifetime): int|false
```suggestion
    public function gc(int $maxlifetime): bool
```
This never returns an int, and I'm pretty sure `false` as a return type is invalid for PHP 8.1 (https://www.php.net/releases/8.2/en.php#null_false_true_types)

2023-01-23 23:06 UTC, GuySartorelli commented on src/Store/DatabaseStore.php
> +        return true;
Why `true` when we're not doing anything? `false` feels like it would be more appropriate?
Or is the assumption that it is always "successful" and hence returns `true`?

Same with `close()` below.

2023-01-23 23:06 UTC, GuySartorelli commented on src/Store/CookieStore.php
> +    public function gc(int $maxlifetime): int|false
Also check others in this PR where `false` is used as a return type.

2023-01-24 22:57 UTC, maxime-rainville commented on src/HybridSession.php
> +    public function read(string $session_id): string|false
This maps to the return type on the [interface](https://www.php.net/manual/en/class.sessionhandlerinterface.php). 

Arguably, that last `return` after the `foreach` should be a `false`.  Don't necessarily want to go down the rabbit hole of debugging the fine print of this right now.

Using the more generic `string|false` gives us the flexibility to change afterwards if we want to.

2023-01-24 23:00 UTC, maxime-rainville commented on src/HybridSession.php
> +    public function gc(int $maxlifetime): int|false
Just tested this on PHP8.1. `int|false` is a valid return type ... `false` isn't.

I don't having a very specific return type here provides much value. The more generic return type gives us the flexibility to change our minds later on.

2023-01-24 23:01 UTC, maxime-rainville commented on src/Store/CookieStore.php
> +    public function gc(int $maxlifetime): int|false
I don't having a very specific return type here provides much value. The more generic return type gives us the flexibility to change our minds later on.

`int|false` is valid return type.

2023-01-24 23:21 UTC, maxime-rainville commented on src/Store/DatabaseStore.php
> +        return true;
The open/close method are meant to lock/unlock a file for read/write operations.

In our case that's nonsensical, because we are using a database. 

Returning `false` is meant to indicate that the operation failed. This doesn't seem appropriate in this context.

I'll had some comments to this effect.

2023-01-24 23:37 UTC, maxime-rainville commented on tests/CookieStoreTest.php
> +    public function testGc()
I added this test to double check that `int|false` is a valid return type. Seems worth keeping it.

2023-01-25 00:07 UTC, GuySartorelli commented
https://github.com/silverstripe/silverstripe-hybridsessions/pull/79#pullrequestreview-1266532907 doesn't seem to have been addressed?

2023-01-25 21:06 UTC, ChloeSartorelli commented on src/HybridSession.php
> +    public function read(string $session_id): string|false
I suppose that's fine

2023-01-25 21:07 UTC, GuySartorelli commented on src/HybridSession.php
> +    public function gc(int $maxlifetime): int
`CookieStore::gc()` has a return type of `int|false`... what's the intention of having this one just be `int`?

2023-01-26 01:26 UTC, maxime-rainville commented on src/HybridSession.php
> +    public function gc(int $maxlifetime): int
I think the intention was for me to blindly apply your previous peer review feedback before I had thought through all the implication :sweat_smile: 

I'll bring it back to what it was.

2023-01-26 05:50 UTC, maxime-rainville reviewed
75% of tho code for the store was covered by the interface.

By the time I was done, it just seemed like it would make more sense to strongly type the entire bloody thing.

2023-01-26 05:50 UTC, maxime-rainville commented on src/Crypto/McryptCrypto.php
> -<?php
This class is deprecated

2023-01-26 05:50 UTC, maxime-rainville commented on src/HybridSession.php
> +        return false;
Returning false is just makes more sense with the underlying interface.

2023-01-26 05:50 UTC, maxime-rainville commented on src/Store/CookieStore.php
> -     * @var HybridSessionStore_Crypto
`HybridSessionStore_Crypto` doesn't actually exists.

2023-01-26 20:58 UTC, GuySartorelli requested changes

2023-01-26 20:58 UTC, GuySartorelli commented on src/HybridSession.php
> +            }
Why are we adding this limitation? If we just need to be sure the method exists, we should use `method_exists() && is_callable()`

2023-01-26 20:58 UTC, GuySartorelli commented on src/HybridSession.php
> +    public static function init(?string $key = null)
```suggestion
    public static function init(string $key = null)
```
I'm 90% sure this works (if it doesn't, just disregard it) - I'm pretty sure PHP allows null as a default value, but then _doesn't_ allow passing it in explicitly.

If that doesn't work, then set the default to an empty string instead.
We should not be saying `null` is a valid value, and then immediately throw an error when someone passes in `null`.

2023-01-26 20:58 UTC, GuySartorelli commented on src/Model/HybridSessionDataObject.php
> + */
This is not standard. If we're going to do this here we should probably as a rule do it everywhere. It's better IMO do just _not_ add these rather than do it inconsistently, as this PHPDoc is likely to end up not being updated.

2023-01-30 09:45 UTC, maxime-rainville commented on src/HybridSession.php
> +            }
`HybridSession` could in theory receive a `SessionHandlerInterface` that has a `setKey` method without extending `BaseStore`. I guess the main argument for checking that it's an instance of `BaseStore` is that we don't know what the paradigm of that `setKey` method would be since it exists outside the context of `BaseStore`.

Don't think it makes much difference either way. In practice, I suspect every single handler passed to this method is a BaseStore ... because otherwise, the previous implementation would have thrown errors in our faces.

I'll change it to `method_exists`.

2023-01-30 09:56 UTC, maxime-rainville commented on src/Model/HybridSessionDataObject.php
> + */
I wouldn't say adding those is a standard. But I would definitively consider it best practice. We've added `@property` annotations on many objects to help with autocomplete:
- https://github.com/creative-commoners/silverstripe-framework/blob/37ff4ee46a9726a763c3ea867f210558b9ea75a3/src/ORM/DataObject.php#L105-L111
- https://github.com/silverstripe/silverstripe-cms/blob/b02beba7babad15a66f9bc91b76872d8496783e6/code/Model/SiteTree.php#L91-L102
- https://github.com/silverstripe/silverstripe-assets/blob/8372705824c93fcbcde42ad5ebc50c3353d0a65f/src/File.php#L82-L89

My general preference is to add them on the spot when I notice they are missing on a class.

2023-01-30 09:58 UTC, maxime-rainville commented on src/HybridSession.php
> +    public static function init(?string $key = null)
Done

2023-01-30 09:59 UTC, maxime-rainville commented on src/Model/HybridSessionDataObject.php
> + */
Happy to scrap it if it's going to be controversial.

2023-01-30 10:31 UTC, dhensby commented on src/Model/HybridSessionDataObject.php
> + */
I think they are super helpful, even if they start to become stale

2023-01-30 20:12 UTC, GuySartorelli commented on src/Model/HybridSessionDataObject.php
> + */
I think if we're going to add them, we should do it with an intentional systematic approach including adding some linting to ensure they are present and consistent with the `$db` values (I suspect we could do that with phpstan).

2023-01-30 20:30 UTC, GuySartorelli commented on src/HybridSession.php
> +            }
It needs to be `method_exists() && is_callable()` - `method_exists()` on its own will return `true` for private methods which obviously can't be called from this scope.

2023-01-30 23:45 UTC, maxime-rainville commented on src/Model/HybridSessionDataObject.php
> + */
I removed the bit since I don't think it's worth holding this PR to fix this issue.

I'm broadly in favour of adding them ad hoc for now. But having a systematic way to add them could be a good thing.

2023-01-30 23:47 UTC, maxime-rainville commented on src/HybridSession.php
> +            }
Updated the `if` statement accordingly. It's worth pointing out that this will be the only instance of `method_exists` and `is_callable` appearing on the same line in our entire codebase.

2023-01-30 23:51 UTC, GuySartorelli commented on src/HybridSession.php
> +            }
In `ViewableData` we identified a scenario where having just `method_exists()` on its own caused problems. I think it's just a matter of us having previously assumed that `method_exists()` did some internal visibility checks which it turns out it _doesn't_ do - so we need to be a little more defensive with it than we have been previously.

It may be worth us going back at some stage and reviewing everywhere we have `method_exists()` but that's a future concern.

2023-01-30 23:52 UTC, GuySartorelli approved these changes
Looks good

2023-01-30 23:52 UTC, merged