FIX Return an emtpy string instead of false from HybridSession::read()
silverstripe/silverstripe-hybridsessions pull request #83
Opened 2023-02-14 23:29 UTC by emteknetnz

Issue https://github.com/silverstripe/silverstripe-hybridsessions/issues/82

2023-02-14 23:59 UTC, michalkleiner commented on README.md
> +* Install with composer using `composer require silverstripe/hybridsessions:^5`
Did you mean ^3 (and the ^5 was because of CMS 5)?
```suggestion
* Install with composer using `composer require silverstripe/hybridsessions:^3`
```

2023-02-15 00:00 UTC, michalkleiner commented on src/HybridSession.php
> +        // The "session" still exists in memory until a new record will be created
```suggestion
        // The "session" still exists in memory until a new record is created
```

2023-02-15 00:00 UTC, GuySartorelli requested changes
Also add a comment above `return true;` in open() something along the lines of
> Our interpretation of "or creates a new one" in https://www.php.net/manual/en/sessionhandlerinterface.open.php allows for the session to have been created in memory, to be stored by the appropriate handler on `session_write_close()`. If the session fails to be written, we return `false` in `write()`, so we will be alerted to there being some error.

Alternatively, we could return `false` from `open()` if _all_ of the stores return `false` which would indicate that none of the stores are going to be able to write the session when the session ends.

Either one of these - a comment explaining our thinking and interpretation of the docs (or returning false if _all_ handlers return false from open) will be fine.

2023-02-15 00:00 UTC, ChloeSartorelli commented on README.md
> +* Install with composer using `composer require silverstripe/hybridsessions:^5`
```suggestion
* Install with composer using `composer require silverstripe/hybridsessions`
```
Composer knows what version is right. Specifying here just gives us another thing we have to change next major.

2023-02-15 00:00 UTC, ChloeSartorelli commented on src/HybridSession.php
> +        return '';
```suggestion
        // Return a blank string if no record was found in any store
        // The "session" still exists in memory until a new record will be created
        // in the first writable store in write()
        // Our interpretation then of "If the record was not found" in https://www.php.net/manual/en/sessionhandlerinterface.read.php
        // is that we have "found" the NEW session in memory.
        // This prevents `PHP Warning: session_start(): Failed to read session data: user`
        // when session_start() is called within SilverStripe\Control\Session::start()
        return '';
```

2023-02-15 00:24 UTC, emteknetnz commented on src/HybridSession.php
> +        // The "session" still exists in memory until a new record will be created
Updated

2023-02-15 00:24 UTC, emteknetnz commented on README.md
> +* Install with composer using `composer require silverstripe/hybridsessions:^5`
Have removed the version as per Guys review below

2023-02-15 00:24 UTC, emteknetnz commented on README.md
> +* Install with composer using `composer require silverstripe/hybridsessions:^5`
Updated

2023-02-15 00:24 UTC, emteknetnz commented on src/HybridSession.php
> +        return '';
Updated

2023-02-15 00:25 UTC, emteknetnz commented
@GuySartorelli I've added the comment to open() rather than changing return types

2023-02-15 00:42 UTC, GuySartorelli approved these changes

2023-02-15 00:42 UTC, merged